#!/system/bin/sh
### SQL Lite Tweaks, by: darky - modified by sbdags

FLY=/data/sqlite.log

busybox rm -f $FLY
busybox touch $FLY

echo "# Fly-On Mod LOGGING ENGINE" | tee -a $FLY
echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Optimizing and defragging your database files,please wait..." | tee -a $FLY;

#Interval between Optimize SQlite runs, in seconds, 108000=30 hours
RUN_EVERY=108000


# echo "";
echo "*********************************************";
echo "Optimizing and defragging your database files (*.db)";
echo "Ignore the 'database disk image is malformed' error";
echo "Ignore the 'no such collation sequence' error";
echo "*********************************************";
echo "";

for i in \
`busybox find /data -iname "*.db"`;
do \
  /system/xbin/sqlite3 $i 'VACUUM;';
  /system/xbin/sqlite3 $i 'REINDEX;';
done;

if [ -d "/dbdata" ]; then
  for i in \
  `busybox find /dbdata -iname "*.db"`;
  do \
    /system/xbin/sqlite3 $i 'VACUUM;';
    /system/xbin/sqlite3 $i 'REINDEX;';
  done;
fi;


if [ -d "/datadata" ]; then
  for i in \
  `busybox find /datadata -iname "*.db"`;
  do \
    /system/xbin/sqlite3 $i 'VACUUM;';
    /system/xbin/sqlite3 $i 'REINDEX;';
  done;
fi;


for i in \
`busybox find /sdcard -iname "*.db"`;
do \
  /system/xbin/sqlite3 $i 'VACUUM;';
  /system/xbin/sqlite3 $i 'REINDEX;';
done;

echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) database files optimization done!" | tee -a $FLY;
