#!/system/bin/sh
# Disable FSync

# Asus Stock Kernel
echo "0" > /sys/devices/virtual/misc/fsynccontrol/fsync_enabled
# CM11 Kernel
echo "0" > /sys/module/sync/parameters/fsync_enabled
# Enable dynamic fsync (default 0)
echo "1" > /sys/kernel/dyn_fsync/Dyn_fsync_active
